#!/usr/bin/env python3
"""Generate the built-in agent-nickname badword list.

Downloads the English + German word lists from the maintained LDNOOBW project
("List of Dirty, Naughty, Obscene and Otherwise Bad Words", CC-BY-4.0) and
renders them into a checked-in Rust source so the list is reproducible, offline,
and NOT user-editable at runtime.

Usage:
  python3 scripts/tools/gen_badwords.py

Output:
  src-tauri/src/agent/badwords.rs
"""

from __future__ import annotations

import sys
import urllib.request
from pathlib import Path

SOURCE = (
    "https://raw.githubusercontent.com/LDNOOBW/"
    "List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/master"
)
LANGS = ("en", "de")
OUT = Path(__file__).resolve().parents[2] / "src-tauri" / "src" / "agent" / "badwords.rs"


def fetch(lang: str) -> list[str]:
    url = f"{SOURCE}/{lang}"
    with urllib.request.urlopen(url, timeout=30) as resp:
        text = resp.read().decode("utf-8")
    return [line.strip().lower() for line in text.splitlines() if line.strip()]


def main() -> None:
    words: set[str] = set()
    for lang in LANGS:
        got = fetch(lang)
        print(f"{lang}: {len(got)} words", file=sys.stderr)
        words.update(got)

    ordered = sorted(words)
    lines = [
        "//! Built-in, NON-user-editable badword list for agent-nickname checks.",
        "//!",
        "//! GENERATED by `scripts/tools/gen_badwords.py` from the LDNOOBW project",
        "//! (en + de): https://github.com/LDNOOBW/"
        "List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words",
        "//! Source list licensed CC-BY-4.0. Do not edit by hand — re-run the script.",
        "",
        f"/// {len(ordered)} lowercased entries (English + German), deduplicated.",
        "pub const BADWORDS: &[&str] = &[",
    ]
    for word in ordered:
        escaped = word.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{escaped}",')
    lines.append("];")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(ordered)} entries)", file=sys.stderr)


if __name__ == "__main__":
    main()
